services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


  # Enable when not using quirrel cli
  # redis:
  #   image: redis
  # quirrel:
  #   image: ghcr.io/quirrel-dev/quirrel:main
  #   environment:
  #     REDIS_URL: redis://redis
  #   ports:
  #     - '9181:9181'